# site properties and page defaults
title: NTU MARS Lab
subtitle: <strong>M</strong>ultimodal embodied <strong>A</strong>I and <strong>R</strong>obotic <strong>S</strong>ystems Lab
description: Multimodal AI and Robotic Systems (MARS) Lab builds multimodal perception and LLMs for robotics and AIoT systems.
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: jianfei.yang@ntu.edu.sg
  orcid: 0000-0002-8075-0439
  google-scholar: V25k08UAAAAJ
  github: Marsrocky
  twitter: Jianfei_AI
  # youtube: NA

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
